version: '2'
services:
    nginx:
        image: "${DOCKER_USER}/lnmp-nginx:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
        volumes:
            - /home/ylsc:/home/ylsc
            - /home/ylsc/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: "${DOCKER_USER}/lnmp-php:v1.2"
        build:
            context: .
            dockerfile: Dockerfile.php
        networks:
            - frontend
            - backend
        volumes:
            - /home/ylsc:/home/ylsc
        environment:
            MYSQL_PASSWORD: Passw0rd
            POSTGRES_PASSWORD: Passw0rd
        depends_on:
            - mysql
            - redis
            - postgres
    mysql:
        image: mysql:5.7
        volumes:
            - /home/ylsc/mysql/mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: Passw0rd
        command: ['mysqld', '--character-set-server=utf8']
        ports:
            - "3306:3306"
        networks:
            - backend
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - backend
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"
        networks:
            - backend
networks:
    frontend:
    backend:
